# Script for applying the Minecraft patch.
# Requires a repository with the Minecraft source code in the "mc" folder
# next to "src".
# Branches in that repo must be set up as follows:
# master: vanilla Minecraft code, as generated by the MCP.
# modded: modified Minecraft code, as generated by the apply-patch script.
# Before running this script, the "modded" branch must be created with
# "master" as its source.

if [ -d ../mc ]; then
	cd ../mc

	git checkout master
	git apply --ignore-space-change --ignore-whitespace ../patch/minecraft.patch

	cp -r . ../tmp

	git reset --hard
	git checkout modded

	cp -r ../tmp/* .
	rm -rf ../tmp
else
	echo "MCP-generated Minecraft source not found!"
	echo "Put it in a folder called \"mc\" next to \"src\"."
fi
