# Script for initializing the Minecraft repository.
# Place the decompiled Minecraft source code, as generated by the MCP, in
# the "mc" folder before running this script!
# The repository that this script creates is required for the apply-patch
# and update-patch scripts. They will not work without it!

if [ -d ../mc ]; then
	cd ../mc

	git init
	git add .
	git commit -a -m "Initial commit"
	git checkout -b modded
	git checkout master
	git apply --ignore-space-change --ignore-whitespace ../patch/minecraft.patch

	cp -r . ../tmp

	git reset --hard
	git checkout modded

	cp -r ../tmp/* .
	rm -rf ../tmp

	git commit -a -m "Add Wurst changes"
else
	echo "MCP-generated Minecraft source not found!"
	echo "Put it in a folder called \"mc\" next to \"src\"."
fi
